add debug step

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -59,6 +59,7 @@ jobs:
           else
             echo "⚠️ No history folder created yet."
           fi
+      
       - name: 🐞 Confirm copied files
         run: ls -la .allure-history
 
@@ -71,7 +72,11 @@ jobs:
       #     else
       #       echo "⚠️ Skipping copy, no history generated."  
       #     fi
-
+      - name: 🐞 Debug Current location and folder content
+        run: |
+          echo "PWD: $(pwd)"
+          ls -la
+          ls -la .allure-history || echo "❌ .allure-history not found here"
       - name: ⬆️ Upload Allure history for next run
         uses: actions/upload-artifact@v4
         with:
